#!/usr/bin/python

#
# M104 P<nn>
#
#  Set extruder temperature (no wait)
#

import hal
import sys

Pval = sys.argv[1]

c = hal.component("_dummy_")
c.ready()
hal.set_p("jsteleop.lcd-out-01", str(float(Pval)/512))
