#!/usr/bin/python

#
# M140 P<nn>
#
#  Set bed temperature (no wait)
#

import hal
import sys

Pval = sys.argv[1]

c = hal.component("_dummy_")
c.ready()
hal.set_p("jsteleop.lcd-out-03", str(float(Pval)))
