#!/usr/bin/python

#
# M190 P<nn>
#
#  Set bed temperature and wait
#

import hal
import sys
import time

Pval = sys.argv[1]
set_point = float(Pval)

c = hal.component("_dummy_")
c.ready()
hal.set_p("jsteleop.lcd-out-03", str(set_point))
hal.set_p("pid.0.command", str(set_point))

while True:
	temp = float(hal.get_value("jsteleop.bed-temperature-in"))
	print(temp)
	if temp >= ( 0.95 * set_point ):
		break
	
	time.sleep(0.1)

